Fix #104, Convert `int32` return codes and variables to `CFE_Status_t`
nasa/DS pull request #105
Opened 2023-04-22 10:53 UTC by thnkslprpt

**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #104
  - most `int32` return codes converted over to `CFE_Status_t`
  - `int32` `status`/`return` variables holding cFE return codes converted to `CFE_Status_t`

**Testing performed**
GitHub CI actions all passing successfully.

**Expected behavior changes**
No change to behavior.
`CFE_Status_t` is more expressive and improves consistency with cFE/cFS.

**Contributor Info**
Avi Weiss @thnkslprpt

2023-05-11 16:52 UTC, chillfig requested changes
Why not update the return type in the function prototype?

https://github.com/nasa/DS/blob/6418e208cb0141896f6a19a3b0422ee10dc1d5cf/fsw/src/ds_table.h#L75

https://github.com/nasa/DS/blob/6418e208cb0141896f6a19a3b0422ee10dc1d5cf/fsw/src/ds_table.h#L188

https://github.com/nasa/DS/blob/6418e208cb0141896f6a19a3b0422ee10dc1d5cf/fsw/src/ds_table.h#L142

https://github.com/nasa/DS/blob/6418e208cb0141896f6a19a3b0422ee10dc1d5cf/fsw/src/ds_table.h#L455

2023-05-11 20:06 UTC, thnkslprpt commented
> Why not update the return type in the function prototype?
> ...

Woops - missed them.
Updated now.

2023-05-16 14:19 UTC, chillfig approved these changes

2023-05-16 14:20 UTC, chillfig commented
> > Why not update the return type in the function prototype?
> > ...
> 
> Woops - missed them. Updated now.

Looks good. Thank you!

2023-05-18 18:43 UTC, merged