Fix #37, Attempt to send message when file complete
nasa/DS pull request #39
Opened 2022-07-21 16:38 UTC by chillfig

**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
A clear and concise description of what the contribution is.
- Fixes #37

**Testing performed**
Steps taken to test the contribution:
1. Build steps '...'
1. Execution steps '...'

**Expected behavior changes**
Generate a message when a file gets completed.

**System(s) tested on**
 - Ubuntu 18.04

**Additional context**
None

**Third party code**
If included, identify any third party code and provide text file of license

**Contributor Info - All information REQUIRED for consideration of pull request**
Justin Figueroa, ASRC Federal

2022-07-21 16:56 UTC, chillfig commented
@skliper Do I manually implement the sub function in apps/ds/unit-test/stubs in this PR?

2022-07-21 19:02 UTC, skliper reviewed
Great start!  See comments.  Since the new function is only called from ds_file.c it doesn't seem like you need to implement a stub.  Just add a unit test within the ds_file_tests.c.  Should also consider adding a requirement and updating the design slides, although the design slides aren't configuration managed within the repo anymore so we'll need to establish a new process.

2022-07-25 20:32 UTC, skliper requested changes

2022-07-25 20:32 UTC, skliper commented on fsw/src/ds_file.c
> +    DS_FileCompletePkt_t DS_FileCompletePkt = {.FileStatus = *FileStatus};
Recommend using the FileInfo structure in the packet and copy elements from FileStatus into FileInfo.

2022-07-25 20:32 UTC, skliper commented on fsw/src/ds_msg.h
> +    DS_AppFileStatus_t FileStatus; /**< \brief Current state of destination file */
Make this a single DS_FileInfo_t element

2022-07-26 16:56 UTC, skliper commented on fsw/src/ds_file.c
> +    DS_FileCompletePkt.FileInfo.OpenState = DS_OPEN;
I think this should be DS_CLOSE?

2022-07-27 16:53 UTC, skliper commented on fsw/src/ds_file.c
> +    DS_FileCompletePkt_t DS_FileCompletePkt;
I think this actually needs to be updated... should be a pointer.

2022-08-02 12:48 UTC, skliper commented on fsw/src/ds_msg.h
> +} DS_FileCompletePktBuf_t;
Add doxygen documentation (this typedef supports CFE SB Allocate buffer use with a DS_FileCompletePkt_t that matches the alignment constraints of a SBBuf)

2022-08-03 14:11 UTC, skliper commented
@dzbaker I think this is ready to merge.

2022-08-03 15:13 UTC, merged